object_types = [
    'Cup',
    'Fan',
    'Stove',
    'Chair',
    'Table',
    'Trash',
    'Bottle',
    'Matchbox',
    'Box',
    'Book',
    'Fridge',
    'Wood',
    'Drawer',
    'Brush',
    'Clothes',
    'Bed',
    'Counter',
    'Fruit',
    'Door',
    'Plate',
    'Vegetable',
    'Cereal',
    'Lamp',
    'Floor',
    'Cleaning',
    'Basket',
    'Washer',
    'Pot',
    'Pan',
    'Dishwasher',
    'Light',
    'Window',
    'Bucket',
    'Plant',
    'Mug',
    'Cupboard',
    'Pen',
    'Sink',
    'Spoon',
    'Fork',
    'Couch',
    'Television',
    'Coffee Maker',
    'Toaster',
    'Microwave',
    'Vacuum Cleaner',
    'Dryer',
    'Iron',
    'Kettle',
    'Candle',
    'Rug',
    'Pillow',
    'Blanket',
    'Curtains',
    'Wall art',
    'Decorative vase',
    'Picture frames',
    'Remote controls',
    'Gaming console',
    'Speakers',
    'Blender',
    'Cutting Board',
    'Knife',
    'Bowl',
    'Toilet',
    'Shower',
    'Bathtub',
    'Towel Rack',
    'Toilet Brush',
    'Soap Dispenser',
    'Toilet Paper Holder',
    'Toothbrush Holder',
    'Mattress',
    'Dresser',
    'Nightstand',
    'Closet',
    'Mirror',
    'Alarm clock',
    'Hanger',
    'Doormat'
]

relations = [
    'Beside',
    'Above',
    'Below',
    'Inside',
    'On',
    'Near'
]
properties = {
    'Fan': ['On', 'Broken', 'White', 'Green', 'Red', 'Yellow', 'Orange', 'Brown', 'Black', 'Blue', 'Large', 'Mobile', 'Wooden', 'Steel', 'Clean'],
    'Stove': ['On', 'Hot', 'Clean', 'Electric', 'Broken', 'White', 'Green', 'Red', 'Yellow', 'Orange', 'Brown', 'Black', 'Blue', 'Large', 'Steel'],
    'Chair': ['Clean', 'Wooden', 'Fabric', 'White', 'Red', 'Green', 'Yellow', 'Blue', 'Black', 'Brown', 'Leather', 'Large', 'Orange', 'Small', 'Purple'],
    'Table': ['Wooden', 'Marble', 'Clean', 'Heavy', 'Black', 'Red', 'Brown', 'Yellow', 'Orange', 'Purple', 'Large', 'Small', 'Round', 'Square', 'White'],
    'Cup': ['Full', 'Broken', 'Hot', 'Clean', 'Glass', 'White', 'Black', 'Brown', 'Red', 'Green', 'Orange', 'Purple', 'Large', 'Small', 'Blue'],
    'Trash': ['Plastic','Steel','Full', 'Large', 'Brown', 'Black', 'Red', 'Green', 'Heavy', 'Blue', 'Purple', 'Yellow', 'Orange', 'Clean', 'White'],
    'Bottle': ['Full', 'Steel', 'Clean', 'Black', 'Brown', 'White', 'Red', 'Yellow', 'Blue', 'Green', 'Orange', 'Purple', 'Large', 'Heavy', 'Cold'],
    'Matchbox': ['Full','Cardboard', 'Large', 'Black', 'Brown', 'Red', 'White', 'Green', 'Blue', 'Yellow', 'Purple', 'Steel', 'Orange', 'Square', 'Wooden'],
    'Box': ['Full', 'Cardboard', 'Green', 'Yellow', 'Wooden', 'Plastic', 'Metal', 'Brown', 'Red', 'Large', 'Heavy', 'Blue', 'Round', 'White', 'Black'],
    'Book': ['Red','White', 'Green', 'Hardcover', 'Yellow', 'Large', 'Torn', 'Brown', 'Black', 'Blue', 'Purple', 'Orange', 'Heavy', 'Clean', 'Open'],
    'Wood': ['Large'],
    'Fridge': ['Open', 'Mini', 'Clean','Empty', 'White', 'Black', 'Red', 'Blue', 'Green', 'Orange', 'Purple', 'Large', 'Yellow', 'Brown', 'Steel'],
    'Drawer': ['Open', 'Full', 'Clean', 'Wooden' 'Metal', 'Large', 'White', 'Black', 'Brown', 'Red', 'Yellow', 'Blue', 'Green', 'Purple', 'Orange'],
    'Brush': ['Clean', 'Large', 'Plastic', 'Wooden', 'White', 'Brown', 'Black', 'Blue', 'Yellow', 'Red', 'Green', 'Purple', 'Orange', 'Heavy', 'Broken'],
    'Clothes': ['Clean', 'Dry', 'White', 'Black', 'Brown', 'Blue', 'Yellow', 'Green', 'Red', 'Purple', 'Orange', 'Torn', 'Large', 'Denim', 'Cotton'],
    'Bed': ['Queen','Twin','King', 'Messy', 'Black', 'White', 'Brown', 'Red', 'Yellow', 'Blue', 'Green', 'Purple', 'Orange', 'Soft', 'Cotton'],
    'Counter': ['Wooden', 'Clean', 'Marble', 'Large', 'White', 'Black', 'Brown', 'Red', 'Green', 'Yellow', 'Blue', 'Purple', 'Orange', 'Square', 'Empty'],
    'Fruit': ['Round','Spoil', 'Yellow', 'Orange', 'Red'],
    'Door': ['Open', 'Blue', 'Wooden', 'Locked', 'White', 'Black', 'Brown', 'Red', 'Yellow', 'Green', 'Orange', 'Purple', 'Large', 'Metal', 'Heavy'],
    'Plate': ['Clean', 'Hot', 'Full', 'Ceramic', 'Plastic', 'Paper', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Purple', 'Large', 'Orange'],
    'Vegetable': ['Spoil', 'Green', 'Large'],
    'Cereal': ['Spoil', 'Opened'],
    'Lamp': ['On', 'Bright', 'Large', 'Heavy', 'Mobile', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Floor': ['Clean','Wooden','Marble', 'White', 'Brown', 'Black', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange','Tile', 'Cold'],
    'Cleaning': ['NoProp'],
    'Basket': ['Plastic', 'Wooden', 'Full', 'Clean', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Large', 'Heavy'],
    'Washer': ['On', 'Full', 'Clean', 'Steel', 'Hot', 'Large', 'White', 'Black', 'Brown', 'Blue', 'Red', 'Yellow', 'Purple', 'Orange'],
    'Pot': ['Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Glass', 'Metal', 'Black', 'White', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Orange'],
    'Pan': ['Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Glass', 'Metal', 'Black', 'White', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Orange'],
    'Dishwasher': ['Open', 'On', 'Full', 'Clean', 'Steel', 'Hot', 'Large', 'White', 'Black', 'Brown', 'Blue', 'Red', 'Yellow', 'Purple', 'Orange'],
    'Light': ['On', 'Bright', 'Mobile', 'Hot', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Clean', 'Green', 'Purple', 'Orange', 'Heavy'],
    'Window': ['Open', 'Clean'],
    'Bucket': ['Full', 'Clean', 'Green', 'Blue', 'Red', 'Steel', 'Wooden', 'Large', 'Heavy', 'White', 'Black', 'Brown', 'Yellow', 'Orange', 'Purple'],
    'Mug': ['Full', 'Plastic', 'Clean', 'Ceramic', 'Black', 'Brown', 'Blue', 'Yellow', 'Red', 'Green', 'White', 'Purple','Orange', 'Hot'],
    'Plant': ['Small', 'Big', 'Green', 'Purple', 'Red','Yellow','Blue'],
    'Cupboard': ['Open', 'Wooden','Clean', 'Full', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange','Large'],
    'Pen': ['Black', 'Blue', 'Red', 'Fountain', 'Gel', 'Large', 'White', 'Green', 'Purple', 'Yellow', 'Orange'],
    'Sink': ['Full', 'Clean', 'Steel', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Metal', 'Ceramic'],
    'Spoon': ['Clean', 'Steel', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Large', 'Wooden'],
    'Fork': ['Clean', 'Steel', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Large', 'Wooden'],
    'Couch': ['Leather', 'Fabric', 'Black', 'Brown', 'Red', 'White', 'Clean', 'Large', 'Heavy', 'Yellow', 'Blue', 'Green', 'Purple', 'Orange'],
    'Television': ['On', 'Loud', 'Bright', 'Large', 'Heavy', 'Flat', 'Black', 'White', 'Brown', 'Red', 'Yellow', 'Blue', 'Green', 'Purple', 'Orange'],
    'Coffee Maker': ['On', 'Full', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Toaster': ['On', 'Empty', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Brown', 'Blue', 'Yellow', 'Red', 'Green', 'Purple', 'Orange'],
    'Microwave': ['On', 'Full', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Vacuum Cleaner': ['On', 'Loud', 'Metal', 'Plastic', 'Large', 'Black', 'Brown', 'White', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Heavy'],
    'Dryer': ['On', 'Hot', 'Full', 'Dry', 'Large', 'Black', 'White', 'Brown', 'Metal', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Loud', 'Orange'],
    'Iron': ['On', 'Hot', 'Black', 'White', 'Clean', 'Large', 'Heavy', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Kettle': ['On', 'Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Black', 'White', 'Metal', 'Electric', 'Brown', 'Red', 'Blue', 'Yellow', 'Green'],
    'Candle': ['On', 'Bright', 'Large', 'Hot', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Orange'],
    'Rug': ['Woolen','Silk', 'Round', 'Square', 'Large', 'Dry', 'White', 'Brown', 'Black', 'Red', 'Blue', 'Yellow', 'Gren', 'Purple', 'Orange'],
    'Pillow': ['Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Blanket': ['Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Curtains': ['Open', 'Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Wall art': ['Clean', 'Large'],
    'Decorative vase': ['Glass', 'Clean', 'Full', 'Large', 'Red', 'Black', 'Brown', 'White', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Picture frames': ['Clean', 'Wooden', 'Glass', 'Large', 'White', 'Brown', 'Black', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Remote controls': ['Black', 'Functional', 'Clean', 'Large', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Gaming console': ['On', 'Loud', 'White', 'Black', 'Brown', 'Red', 'Yellow', 'Blue', 'Purple', 'Green', 'Orange'],
    'Speakers': ['On', 'Loud', 'Clean', 'Large', 'Heavy', 'Wooden', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple'],
    'Blender': ['On', 'Full', 'Clean', 'Loud', 'Metal', 'Plastic', 'Glass', 'Black', 'White', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Orange', 'Purple'],
    'Cutting Board': ['Clean', 'Wooden', 'Large', 'Plastic', 'Brown', 'Red', 'Green', 'Blue', 'Black', 'White', 'Yellow', 'Purple', 'Orange'],
    'Knife': ['Clean', 'Sharp', 'Serated', 'Metal', 'Plastic', 'Large', 'White', 'Black', 'Brown', 'Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
    'Bowl': ['Full', 'Broken', 'Hot', 'Clean', 'White', 'Brown', 'Red', 'Ceramic', 'Large', 'Heavy', 'Metal', 'Plastic', 'Green', 'Black', 'Purple', 'Orange'],
    'Toilet': ['Clean', 'Cold', 'Ceramic', 'White', 'Black', 'Broken', 'Clogged', 'Full', 'Green', 'Red', 'Heavy'],
    'Shower': ['On', 'Clean', 'Warm', 'Ceramic', 'Tile', 'Red', 'White', 'Black', 'Green', 'Broken'],
    'Bathtub': ['Full', 'Clean', 'Warm', 'Ceramic', 'Tile', 'Red', 'White', 'Black', 'Green', 'Broken'],
    'Towl Rack': ['Full', 'Clean', 'Warm', 'Ceramic', 'Tile', 'Red', 'White', 'Black', 'Green', 'Broken', 'Metal', 'Purple'],
    'Toilet Brush': ['Clean', 'White', 'Broken', 'Plastic', 'Metal', 'Black', 'Brown', 'Large', 'Green' 'Red', 'Orange', 'Purple', 'Yellow', 'Blue'],
    'Soap Dispenser': ['Clean', 'Full', 'Large', 'Plastic', 'Metal', 'Ceramic', 'Red', 'White', 'Blue', 'Black', 'Green','Purple', 'Orange', 'Yellow', 'Brown'],
    'Toilet Paper Holder': ['Full', 'Clean', 'Steel', 'Ceramic', 'Metal', 'Large', 'Broken', 'White', 'Red', 'Blue', 'Yellow', 'Purple', 'Green', 'Orange', 'Brown'],
    'Toothbrush Holder': ['Clean', 'Full', 'Broken', 'Plastic', 'White', 'Brown', 'Black', 'Red', 'Green', 'Blue', 'Purple', 'Yellow', 'Orange'],
    'Mattress': ['Soft', 'Clean', 'Large', 'Green', 'Purple', 'Yellow', 'Brown', 'White', 'Black', 'Broken'],
    'Dresser': ['Full', 'Open', 'Clean', 'Wooden', 'Metal','Large', 'Heavy', 'White', 'Brown', 'Black', 'Green', 'Red', 'Yellow','Orange', 'Purple'],
    'Nightstand': ['Full', 'Open', 'Clean', 'Large', 'Wooden', 'Metal', 'Glass', 'Broken', 'White', 'Black', 'Brown', 'Red', 'Green', 'Purple', 'Orange', 'Yellow'],
    'Closet': ['Open', 'Full', 'Messy', 'Wooden', 'Glass', 'Red', 'Yellow', 'Blue', 'Green', 'Purple', 'Yellow', 'Large','Orange'],
    'Mirror': ['Clean','Large', 'Heavy'],
    'Alarm clock': ['On','Bright', 'Loud', 'Plastic', 'Metal', 'Broken', 'White', 'Black', 'Brown', 'Red', 'Blue','Green', 'Yellow', 'Orange', 'Purple'],
    'Hanger': ['Full', 'Large', 'Metal', 'Plastic', 'White', 'Brown', 'Black', 'Red', 'Blue', 'Yellow', 'Green', 'Orange', 'Purple'],
    'Doormat': ['Clean', 'Large', 'Wet', 'Black', 'Brown', 'White', 'Blue', 'Red', 'Orange', 'Yellow', 'Green', 'Purple']
}
actions = {
    'Fan': ['On', 'Off'],
    'Stove': ['On', 'Off'],
    'Chair': ['Grab', 'Place','Clean'],
    'Table': ['NoAct'],
    'Cup': ['Grab', 'Place', 'Fill', 'Empty', 'Break', 'Clean'],
    'Trash': ['NoAct'],
    'Bottle': ['Grab', 'Place'],
    'Matchbox': ['Grab', 'Place'],
    'Book': ['Grab', 'Place'],
    'Box': ['NoAct'],
    'Wood': ['Grab', 'Place'],
    'Fridge': ['Open', 'Close'],
    'Drawer': ['Open','Close'],
    'Brush' : ['Grab', 'Place'],
    'Clothes': ['Clean', 'Grab', 'Place'],
    'Bed': ['NoAct'],
    'Counter': ['NoAct'],
    'Fruit': ['Grab', 'Place'],
    'Door': ['Open', 'Close'],
    'Plate': ['Grab', 'Place', 'Clean'],
    'Spoon': ['Grab', 'Place', 'Clean'],
    'Fork': ['Grab', 'Place', 'Clean'],
    'Vegetable': ['Grab', 'Place'],
    'Cereal': ['Grab', 'Place'],
    'Lamp': ['Grab', 'Place', 'On', 'Off'],
    'Floor': ['Clean'],
    'Cleaning': ['Grab', 'Place'],
    "Basket": ['NoAct'],
    'Washer': ['On', 'Off'],
    'Pot': ['Grab', 'Place'],
    'Pan': ['Grab', 'Place'],
    'Dishwasher': ['On', 'Off', 'Open', 'Close'],
    'Light': ['On', 'Off'],
    'Window': ['Open', 'Close', 'Clean'],
    'Bucket': ['Fill', 'Empty', 'Grab', 'Place'],
    'Mug': ['Fill', 'Empty', 'Grab', 'Place'],
    'Plant': ['Pour'],
    'Cupboard': ['Open','Close'],
    'Pen': ['Grab', 'Place'],
    'Sink': ['NoAct'],
    'Couch': ['NoAct'],
    'Television': ['On', 'Off'],
    'Coffee Maker': ['On', 'Off'],
    'Toaster': ['On', 'Off'],
    'Microwave': ['On', 'Off'],
    'Vacuum Cleaner': ['On', 'Off'],
    'Dryer': ['On', 'Off'],
    'Iron': ['On', 'Off'],
    'Kettle': ['On', 'Off'],
    'Candle': ['On', 'Off'],
    'Rug': ['Grab','Place'],
    'Pillow': ['Grab','Place'],
    'Blanket': ['Grab','Place'],
    'Curtains': ['Open','Close'],
    'Wall art': ['NoAct'],
    'Decorative vase': ['Grab', 'Place'],
    'Picture frames': ['NoAct'],
    'Remote controls': ['On', 'off'],
    'Gaming console': ['On', 'Off'],
    'Speakers': ['On','Off'],
    'Blender': ['On', 'off'],
    'Cutting Board': ['Grab', 'Place'],
    'Knife': ['Grab', 'Place'],
    'Bowl': ['Grab', 'Place', 'Fill'],
    'Toilet': ['Clean'],
    'Shower': ['On', 'Off'],
    'Bathtub': ['Fill'],
    'Towel Rack': ['NoAct'],
    'Toilet Brush': ['Grab', 'Place'],
    'Soap Dispenser': ['NoAct'],
    'Toilet Paper Holder': ['NoAct'],
    'Toothbrush Holder': ['NoAct'],
    'Mattress': ['NoAct'],
    'Dresser': ['NoAct'],
    'Nightstand': ['NoAct'],
    'Closet': ['Open', 'Close'],
    'Mirror': ['NoAct'],
    'Alarm clock': ['On','Off'],
    'Hanger': ['Grab', 'Place'],
    'Doormat': ['Grab', 'Place', 'Clean']
}

locations = [
    'Bedroom',
    'Kitchen',
    'Washroom',
    'Livingroom'
]

props = {
    'On': ['Lamp','Fan', 'Stove', 'Washer', 'Dishwasher','Light','Television','Coffee Maker',
     'Toaster','Microwave','Vacuum Cleaner','Dryer','Iron','Kettle','Candle', 'Gaming console',
      'Speakers', 'Blender', 'Shower', 'Alarm clock'],
    'Full': ['Cup', 'Box', 'Bucket', 'Mug', 'Trash','Sink', 'Bowl', 'Bathtub', 'Towel Rack',
    'Dresser', 'Nightstand', 'Hanger'],
    'Broken': ['Cup', 'Bowl'],
    'Hot': ['Cup', 'Pot', 'Pan', 'Bowl'],
    'Open': ['Window', 'Fridge', 'Drawer', 'Door', 'Dishwasher', 'Cupboard', 'Curtains', 'Closet'],
    'Red': ['Book'],
    'White': ['Book'],
    'Green': ['Book', 'Vegetable'],
    'Clean': ['Clothes', 'Chair', 'Cup', 'Plate', 'Floor', 'Spoon', 'Fork', 'Window', 
    'Bowl', 'Toilet', 'Doormat'],
    'Blue': ['Door'],
    'Steel': ['Fork', 'Spoon', 'Trash'],
    'Plastic': ['Fork', 'Spoon', 'Mug', 'Basket', 'Trash'],
    'Fountain': ['Pen'], 
    'Gel': ['Pen'],
    'Wooden': ['Cupboard', 'Basket', 'Floor', 'Table'],
    'Small': ["Plant"],
    'Big': ['Plant'],
    'Marble': ['Floor', 'Table'],
    'Round': ['Fruit'],
    'Cardboard': ['Box'],
    'Mini': ['Fridge'],
    'Queen': ['Bed'],
    'Twin': ['Bed'],
    'King': ['Bed'],
    'Woolen': ['Rug'],
    'Silk': ['Rug', 'Blanket'],
    'Cotton': ['Blanket'],
    'Glass': ['Decorative vase'],
    'Dry': ['Clothes'],
    'Spoil': ['Fruit','Vegetable']
}
