object_types = [
    'Cup',
    'Fan',
    'Stove',
    'Chair',
    'Table',
    'Trash',
    'Bottle',
    'Matchbox',
    'Box',
    'Book',
    'Fridge',
    'Wood',
    'Drawer',
    'Brush',
    'Clothes',
    'Bed',
    'Counter',
    'Fruit',
    'Door',
    'Plate',
    'Vegetable',
    'Cereal',
    'Lamp',
    'Floor',
    'Cleaning',
    'Basket',
    'Washer',
    'Pot',
    'Pan',
    'Dishwasher',
    'Light',
    'Window',
    'Bucket',
    'Plant',
    'Mug',
    'Cupboard',
    'Pen',
    'Sink',
    'Spoon',
    'Fork',
    'Couch',
    'Television',
    'Coffee Maker',
    'Toaster',
    'Microwave',
    'Vacuum Cleaner',
    'Dryer',
    'Iron',
    'Kettle',
    'Candle',
    'Rug',
    'Pillow',
    'Blanket',
    'Curtains',
    'Wall art',
    'Decorative vase',
    'Picture frames',
    'Remote controls',
    'Gaming console',
    'Speakers'
]

relations = [
    'Beside',
    'Above',
    'Below',
    'Inside',
    'On',
    'Near'
]
properties = {
    'Fan': ['On', 'Broken', 'White', 'Green', 'Red', 'Black', 'Blue', 'Large', 'Wooden', 'Clean'],
    'Stove': ['On', 'Hot', 'Clean', 'Electric', 'Broken', 'White', 'Black', 'Blue', 'Large', 'Steel'],
    'Chair': ['Clean', 'Wooden', 'Fabric', 'White', 'Red', 'Yellow', 'Blue', 'Black', 'Brown','Large'],
    'Table': ['Wooden', 'Marble', 'Clean', 'Black', 'Brown', 'Large', 'Small', 'Round', 'Square', 'White'],
    'Cup': ['Full', 'Broken', 'Hot', 'Clean', 'Glass', 'White', 'Black', 'Brown', 'Red', 'Large'],
    'Trash': ['Plastic','Steel','Full', 'Large', 'Brown', 'Black', 'Heavy', 'Blue', 'Clean', 'White'],
    'Bottle': ['Full', 'Steel', 'Clean', 'Black','Blue', 'Orange', 'Purple', 'Large', 'Heavy', 'Cold'],
    'Matchbox': ['Full','Cardboard', 'Large', 'Black', 'Brown','Purple', 'Steel', 'Orange', 'Square', 'Wooden'],
    'Box': ['Full', 'Cardboard', 'Green', 'Yellow', 'Wooden', 'Plastic', 'Metal', 'Brown','Large', 'Heavy'],
    'Book': ['Red','White', 'Green', 'Large', 'Black', 'Blue', 'Orange', 'Heavy', 'Clean', 'Open'],
    'Wood': ['Large'],
    'Fridge': ['Open', 'Mini', 'Clean','Empty', 'White', 'Purple', 'Large', 'Yellow', 'Brown', 'Steel'],
    'Drawer': ['Open', 'Full', 'Clean', 'Wooden' 'Metal', 'Large', 'White', 'Black', 'Brown', 'Red'],
    'Brush': ['Clean', 'Large', 'Plastic', 'Wooden', 'White', 'Brown', 'Black', 'Orange', 'Heavy', 'Broken'],
    'Clothes': ['Clean', 'Dry', 'White', 'Black', 'Green', 'Red', 'Purple', 'Torn', 'Large', 'Cotton'],
    'Bed': ['Queen','Twin','King', 'Messy', 'Black', 'White', 'Brown', 'Orange', 'Soft', 'Cotton'],
    'Counter': ['Wooden', 'Clean', 'Marble', 'Large', 'White', 'Black', 'Brown', 'Orange', 'Square', 'Empty'],
    'Fruit': ['Round','Spoil'],
    'Door': ['Open', 'Blue', 'Wooden', 'Locked', 'White', 'Black', 'Brown', 'Red', 'Large', 'Metal'],
    'Plate': ['Clean', 'Hot', 'Full', 'Ceramic', 'Plastic', 'Paper', 'White', 'Purple', 'Large', 'Orange'],
    'Vegetable': ['Spoil'],
    'Cereal': ['Opened'],
    'Lamp': ['On', 'Bright', 'Large', 'Heavy', 'Mobile', 'White', 'Red', 'Blue', 'Yellow', 'Green'],
    'Floor': ['Clean','Wooden','Marble', 'White', 'Brown', 'Black', 'Orange','Tile', 'Cold'],
    'Cleaning': ['NoProp'],
    'Basket': ['Plastic', 'Wooden', 'Full', 'Clean', 'White', 'Black', 'Green', 'Purple', 'Orange', 'Large'],
    'Washer': ['On', 'Full', 'Clean', 'Steel', 'Hot', 'Large', 'White', 'Black', 'Brown', 'Blue', 'Red'],
    'Pot': ['Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Glass', 'Metal', 'Black','Green', 'Orange'],
    'Pan': ['Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Glass', 'Metal', 'Black', 'Green', 'Orange'],
    'Dishwasher': ['Open', 'On', 'Full', 'Clean', 'Steel', 'Hot', 'Large', 'White', 'Black', 'Brown'],
    'Light': ['On', 'Bright', 'Mobile', 'Hot', 'White', 'Black', 'Red', 'Blue', 'Yellow', 'Clean'],
    'Window': ['Open', 'Clean'],
    'Bucket': ['Full', 'Clean', 'Green', 'Blue', 'Red', 'Steel', 'Wooden', 'Large', 'Heavy', 'White'],
    'Mug': ['Full', 'Plastic', 'Clean', 'Ceramic', 'Black', 'Brown', 'Blue', 'Yellow', 'Hot'],
    'Plant': ['Small', 'Big', 'Green', 'Purple', 'Red','Yellow','Blue'],
    'Cupboard': ['Open', 'Wooden','Clean', 'Full', 'White', 'Black', 'Brown', 'Red','Large'],
    'Pen': ['Black', 'Blue', 'Red', 'Fountain', 'Gel', 'Large', 'Green', 'Purple', 'Yellow', 'Orange'],
    'Sink': ['Full', 'Clean', 'Steel', 'Black', 'Brown', 'Purple', 'Orange', 'Metal', 'Ceramic'],
    'Spoon': ['Clean', 'Steel', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Large', 'Wooden'],
    'Fork': ['Clean', 'Steel', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Large', 'Wooden'],
    'Couch': ['Leather', 'Fabric', 'Black', 'Brown', 'Red', 'White', 'Clean', 'Large', 'Heavy'],
    'Television': ['On', 'Loud', 'Bright', 'Large', 'Heavy', 'Flat', 'Black', 'White', 'Brown', 'Red'],
    'Coffee Maker': ['On', 'Full', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Purple', 'Orange'],
    'Toaster': ['On', 'Empty', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Brown', 'Blue'],
    'Microwave': ['On', 'Full', 'Clean', 'Hot', 'Metal', 'Plastic', 'Black', 'White', 'Brown', 'Red'],
    'Vacuum Cleaner': ['On', 'Loud', 'Metal', 'Plastic', 'Large', 'Black', 'Brown','Orange', 'Heavy'],
    'Dryer': ['On', 'Hot', 'Full', 'Dry', 'Large', 'Black', 'White', 'Metal', 'Purple', 'Loud', 'Orange'],
    'Iron': ['On', 'Hot', 'Black', 'White', 'Clean', 'Large', 'Heavy', 'Brown', 'Red', 'Blue'],
    'Kettle': ['On', 'Hot', 'Full', 'Clean', 'Large', 'Heavy', 'Black', 'White', 'Metal', 'Electric'],
    'Candle': ['On', 'Bright', 'Large', 'Hot', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Orange'],
    'Rug': ['Woolen','Silk', 'Round', 'Square', 'Large', 'Dry', 'White', 'Brown', 'Black', 'Red'],
    'Pillow': ['Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red', 'Blue'],
    'Blanket': ['Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red', 'Blue'],
    'Curtains': ['Open', 'Soft', 'White', 'Clean', 'Cotton', 'Silk', 'Large', 'Black', 'Brown', 'Red'],
    'Wall art': ['Clean', 'Large'],
    'Decorative vase': ['Glass', 'Clean', 'Full', 'Large', 'Red', 'Black', 'Brown', 'White', 'Blue', 'Yellow'],
    'Picture frames': ['Clean', 'Wooden', 'Glass', 'Large', 'White', 'Brown', 'Black', 'Red', 'Blue', 'Yellow'],
    'Remote controls': ['Black', 'Functional', 'Clean', 'Large', 'Plastic', 'White', 'Black', 'Brown', 'Red', 'Blue'],
    'Gaming console': ['On', 'Loud', 'White', 'Black', 'Brown', 'Red', 'Yellow', 'Blue', 'Purple', 'Green', 'Orange'],
    'Speakers': ['On', 'Loud', 'Clean', 'Large', 'Heavy', 'Wooden', 'White', 'Black', 'Brown', 'Red']
}
actions = {
    'Fan': ['On', 'Off'],
    'Stove': ['On', 'Off'],
    'Chair': ['Grab', 'Place','Clean'],
    'Table': ['NoAct'],
    'Cup': ['Grab', 'Place', 'Fill', 'Empty', 'Break', 'Clean'],
    'Trash': ['NoAct'],
    'Bottle': ['Grab', 'Place'],
    'Matchbox': ['Grab', 'Place'],
    'Book': ['Grab', 'Place'],
    'Box': ['NoAct'],
    'Wood': ['Grab', 'Place'],
    'Fridge': ['Open', 'Close'],
    'Drawer': ['Open','Close'],
    'Brush' : ['Grab', 'Place'],
    'Clothes': ['Clean', 'Grab', 'Place'],
    'Bed': ['NoAct'],
    'Counter': ['NoAct'],
    'Fruit': ['Grab', 'Place'],
    'Door': ['Open', 'Close'],
    'Plate': ['Grab', 'Place', 'Clean'],
    'Spoon': ['Grab', 'Place', 'Clean'],
    'Fork': ['Grab', 'Place', 'Clean'],
    'Vegetable': ['Grab', 'Place'],
    'Cereal': ['Grab', 'Place'],
    'Lamp': ['Grab', 'Place', 'On', 'Off'],
    'Floor': ['Clean'],
    'Cleaning': ['Grab', 'Place'],
    "Basket": ['NoAct'],
    'Washer': ['On', 'Off'],
    'Pot': ['Grab', 'Place'],
    'Pan': ['Grab', 'Place'],
    'Dishwasher': ['On', 'Off', 'Open', 'Close'],
    'Light': ['On', 'Off'],
    'Window': ['Open', 'Close', 'Clean'],
    'Bucket': ['Fill', 'Empty', 'Grab', 'Place'],
    'Mug': ['Fill', 'Empty', 'Grab', 'Place'],
    'Plant': ['Pour'],
    'Cupboard': ['Open','Close'],
    'Pen': ['Grab', 'Place'],
    'Sink': ['NoAct'],
    'Couch': ['NoAct'],
    'Television': ['On', 'Off'],
    'Coffee Maker': ['On', 'Off'],
    'Toaster': ['On', 'Off'],
    'Microwave': ['On', 'Off'],
    'Vacuum Cleaner': ['On', 'Off'],
    'Dryer': ['On', 'Off'],
    'Iron': ['On', 'Off'],
    'Kettle': ['On', 'Off'],
    'Candle': ['On', 'Off'],
    'Rug': ['Grab','Place'],
    'Pillow': ['Grab','Place'],
    'Blanket': ['Grab','Place'],
    'Curtains': ['Open','Close'],
    'Wall art': ['NoAct'],
    'Decorative vase': ['Grab', 'Place'],
    'Picture frames': ['NoAct'],
    'Remote controls': ['On', 'off'],
    'Gaming console': ['On', 'Off'],
    'Speakers': ['On','Off']
}

locations = [
    'Bedroom',
    'Kitchen',
    'Washroom',
    'Livingroom'
]

props = {
    'On': ['Lamp','Fan', 'Stove', 'Washer', 'Dishwasher','Light','Television','Coffee Maker', 'Toaster','Microwave','Vacuum Cleaner','Dryer','Iron','Kettle','Candle', 'Gaming console', 'Speakers'],
    'Full': ['Cup', 'Box', 'Bucket', 'Mug', 'Trash','Sink'],
    'Broken': ['Cup'],
    'Hot': ['Cup', 'Pot', 'Pan'],
    'Open': ['Window', 'Fridge', 'Drawer', 'Door', 'Dishwasher', 'Cupboard', 'Curtains'],
    'Red': ['Book'],
    'White': ['Book'],
    'Green': ['Book', 'Vegetable'],
    'Clean': ['Clothes', 'Chair', 'Cup', 'Plate', 'Floor', 'Spoon', 'Fork', 'Window'],
    'Blue': ['Door'],
    'Steel': ['Fork', 'Spoon', 'Trash'],
    'Plastic': ['Fork', 'Spoon', 'Mug', 'Basket', 'Trash'],
    'Fountain': ['Pen'], 
    'Gel': ['Pen'],
    'Wooden': ['Cupboard', 'Basket', 'Floor', 'Table'],
    'Small': ["Plant"],
    'Big': ['Plant'],
    'Marble': ['Floor', 'Table'],
    'Round': ['Fruit'],
    'Cardboard': ['Box'],
    'Mini': ['Fridge'],
    'Queen': ['Bed'],
    'Twin': ['Bed'],
    'King': ['Bed'],
    'Woolen': ['Rug'],
    'Silk': ['Rug', 'Blanket'],
    'Cotton': ['Blanket'],
    'Glass': ['Decorative vase'],
    'Dry': ['Clothes'],
    'Spoil': ['Fruit','Vegetable']
}
