object_types = [
    'Cup',
    'Fan',
    'Stove',
    'Chair',
    'Table',
    'Trash',
    'Bottle',
    'Matchbox',
    'Box',
    'Book',
    'Fridge',
    'Wood',
    'Drawer',
    'Brush',
    'Clothes',
    'Bed',
    'Counter',
    'Fruit',
    'Door',
    'Plate',
    'Vegetable',
    'Cereal',
    'Lamp',
    'Floor',
    'Cleaning',
    'Basket',
    'Washer',
    'Pot',
    'Pan',
    'Pillow',
    'Dishwasher',
    'Light',
    'Window',
    'Bucket',
    'Plant',
    'Mug',
    'Cupboard',
    'Pen',
    'Sink',
    'Spoon',
    'Fork'
]

relations = [
    'Beside',
    'Above',
    'Below',
    'Inside',
    'On',
    'Near'
]
properties = {
    'Fan': ['On', 'White', 'Black', 'Wooden', 'Clean'],
    'Stove': ['On', 'Hot', 'Clean', 'Electric', 'Broken'],
    'Chair': ['Clean', 'Fabric', 'Black', 'Brown','Large'],
    'Table': ['Wooden', 'Clean','Large','Round', 'White'],
    'Cup': ['Full', 'Broken', 'Hot', 'Clean', 'Glass'],
    'Trash': ['Steel','Full', 'Large', 'Black','Clean'],
    'Bottle': ['Full', 'Steel', 'Clean','Large', 'Cold'],
    'Matchbox': ['Full', 'Black', 'Brown', 'Square', 'Wooden'],
    'Box': ['Full', 'Cardboard', 'Plastic', 'Brown','Large'],
    'Book': ['Red','White', 'Green', 'Large', 'Open'],
    'Wood': ['NoProp'],
    'Fridge': ['Open', 'Mini', 'Clean', 'Large', 'Steel'],
    'Drawer': ['Open', 'Full', 'Clean', 'Wooden', 'White'],
    'Brush': ['Clean', 'Large', 'Plastic', 'Black', 'Broken'],
    'Clothes': ['Clean', 'Dry', 'White', 'Large', 'Cotton'],
    'Bed': ['Queen','Twin','King', 'White', 'Soft'],
    'Counter': ['Wooden', 'Clean', 'Marble', 'Large', 'Empty'],
    'Fruit': ['Spoil'],
    'Door': ['Open', 'Blue', 'Wooden', 'Large', 'Metal'],
    'Plate': ['Clean', 'Hot', 'Full', 'Ceramic', 'Large'],
    'Vegetable': ['Spoil'],
    'Cereal': ['NoProp'],
    'Lamp': ['On', 'Bright', 'Large', 'Red', 'Green'],
    'Floor': ['Clean','Wooden','Marble', 'Tile', 'Cold'],
    'Cleaning': ['NoProp'],
    'Basket': ['Plastic', 'Wooden', 'Full', 'Clean', 'Large'],
    'Washer': ['On', 'Full', 'Clean', 'Steel', 'Hot', 'Large'],
    'Pot': ['Hot', 'Full', 'Clean', 'Large', 'Black'],
    'Pan': ['Hot', 'Full', 'Clean', 'Large', 'Black'],
    'Dishwasher': ['Open', 'On', 'Full', 'Clean','Large'],
    'Light': ['On', 'Bright', 'Mobile', 'Hot', 'Clean'],
    'Window': ['Open', 'Clean'],
    'Bucket': ['Full', 'Clean', 'Steel', 'Wooden', 'Large'],
    'Mug': ['Full', 'Plastic', 'Clean', 'Ceramic', 'Hot'],
    'Pillow': ['Soft'],
    'Plant': ['Small', 'Big', 'Green', 'Purple', 'Red'],
    'Cupboard': ['Open', 'Wooden','Clean', 'Full'],
    'Pen': ['Black', 'Blue', 'Red', 'Fountain', 'Gel'],
    'Sink': ['Full', 'Clean', 'Steel', 'Metal', 'Ceramic'],
    'Spoon': ['Clean', 'Steel', 'Plastic', 'Large', 'Wooden'],
    'Fork': ['Clean', 'Steel', 'Plastic', 'Large', 'Wooden']
}
actions = {
    'Fan': ['On', 'Off'],
    'Stove': ['On', 'Off'],
    'Chair': ['Grab', 'Place','Clean'],
    'Table': ['NoAct'],
    'Cup': ['Grab', 'Place', 'Fill', 'Empty', 'Break', 'Clean'],
    'Trash': ['NoAct'],
    'Bottle': ['Grab', 'Place'],
    'Matchbox': ['Grab', 'Place'],
    'Book': ['Grab', 'Place'],
    'Box': ['NoAct'],
    'Wood': ['Grab', 'Place'],
    'Fridge': ['Open', 'Close'],
    'Drawer': ['Open','Close'],
    'Brush' : ['Grab', 'Place'],
    'Clothes': ['Clean', 'Grab', 'Place'],
    'Bed': ['NoAct'],
    'Counter': ['NoAct'],
    'Fruit': ['Grab', 'Place'],
    'Door': ['Open', 'Close'],
    'Plate': ['Grab', 'Place', 'Clean'],
    'Spoon': ['Grab', 'Place', 'Clean'],
    'Fork': ['Grab', 'Place', 'Clean'],
    'Vegetable': ['Grab', 'Place'],
    'Cereal': ['Grab', 'Place'],
    'Lamp': ['Grab', 'Place', 'On', 'Off'],
    'Floor': ['Clean'],
    'Cleaning': ['Grab', 'Place'],
    "Basket": ['NoAct'],
    'Washer': ['On', 'Off'],
    'Pot': ['Grab', 'Place'],
    'Pan': ['Grab', 'Place'],
    'Dishwasher': ['On', 'Off', 'Open', 'Close'],
    'Light': ['On', 'Off'],
    'Window': ['Open', 'Close', 'Clean'],
    'Bucket': ['Fill', 'Empty', 'Grab', 'Place'],
    'Mug': ['Fill', 'Empty', 'Grab', 'Place'],
    'Plant': ['Pour'],
    'Pillow': ['Grab','Place'],
    'Cupboard': ['Open','Close'],
    'Pen': ['Grab', 'Place'],
    'Sink': ['NoAct']
}

locations = [
    'Bedroom',
    'Kitchen',
    'Washroom',
    'Livingroom'
]

props = {
    'On': ['Lamp','Fan', 'Stove', 'Washer', 'Dishwasher','Light'],
    'Full': ['Cup', 'Box', 'Bucket', 'Mug'],
    'Broken': ['Cup'],
    'Hot': ['Cup'],
    'Open': ['Window', 'Fridge', 'Drawer', 'Door', 'Dishwasher', 'Cupboard'],
    'Red': ['Book'],
    'White': ['Book'],
    'Green': ['Book'],
    'Clean': ['Clothes', 'Chair', 'Cup', 'Plate', 'Floor', 'Spoon', 'Fork', 'Window'],
    'Blue': ['Door'],
    'Dry': ['Clothes'],
    'Spoil': ['Fruit','Vegetable']
}
